---
title: "DM2 Evaluation de performance"
author: "Mammar & Barthelemy"
date: "22/03/2015"
output: html_document
---
Simulation de la file LIFO :

**Question 1**  -  *Etudions la file M/M/1 - LIFO*


```{r}
library(plyr)
library(ggplot2)

Service <- function(n=1,typeservice,x,y) {
# genere un temps de service
  switch(typeservice,
         det = rep(1,n),
         uni = runif(n,x,y),
         gamma = rgamma(n,shape=x,scale=y),
         exp = rexp(n,x)
         )
}

FileLIFO <- function(n,lambda,typeservice,x,y,policy) {
    # simulates a M/GI/1 LIFO queue with different preemption policy
    # parameters:
    #    n :  total number of jobs
    #    lambda : arrival rate
    #    typeservice : service law (det uni gamma exp)
    #    x ,y : parameters of the service law
    #    policy: npmtn, pmtn, pmtn_restart, pmtn_reset
    # return value:
    #    vector with response time of each task assuming the queue is initially empty
    set.seed(10)                #in order to have the same time service each call with the same lambda, x, y
    A <- rexp(n,lambda)         # inter arrival
    t1 <- cumsum(A)             # arrival dates
    t2 <- rep(NA,n)             # completion dates
    S <- Service(n,typeservice,x,y) # initial service times
    
    #### Variables that define the state of the queue
    t = 0               # current time
    remaining = rep(NA,n)  # how much work remains to do for each task
    running = NA        # index of the currently running task
    waiting = c()       # stack with tasks which have arrived and have not been completed yet
    next_arrival = 1    # index of the next task to arrive
    sys_vide = 0        # by curiosity let's count the number of times the system is empty
    sys_interrupted = 0 # by curiosity let's count the number of times the system is interrupted
    used = rep(0, n)    # by curiosity let's count the total of time used by a process (including its restart)
    #interrupted = data.frame()  # by curiosity let's save the preemptions for counting them later
    
    
    #### A few useful local functions 
    run_task = function() { # runs the last task of the waiting list
      #if there is still a process in the stack to run, we take the last one in
      if(length(waiting)>0) {
        index = length(waiting)
        running = waiting[index] #it unstacks the last process received to update its remainning time
        #At first loop it takes S[running], but after remaining[running] is returned
        remaining[running] <<- min(S[running],remaining[running],na.rm=T)
        
        #return the waiting index of the process with a minimum remaining time > 0 : depending on the policy chosen
        switch(policy,
                        srpt_pmtn = 
                          { #we elect the min between the new and current request by comparing their remaining time
                            if (index >= 2) { 
                              if (remaining[waiting[index-1]] <= remaining[waiting[index]]) 
                                index = (index - 1)
                            }
                          },
                       
                        spt_pmtn = 
                          { #we elect the min between the new and current request by comparing their service time
                            if (index >= 2) { 
                              if (S[waiting[index-1]] <= S[waiting[index]]) 
                              index = (index - 1)
                            }
                          },
                       
                        spt = 
                          { #we elect the first shortest remaining time process, among all the waiting processes
                            min_process = which(remaining==min(remaining[remaining>0], na.rm=T))
                            index = (which(waiting == min_process))[1]
                          }
                )
        running <<- waiting[index]        
        waiting <<- waiting[-index] #renvoie le tableau privé de l'element a la position index 
      }
    }

    push_task = function() { # insert the next_arrival-th task to the waiting list
                             # and run it if there is preemption
      if(policy != "spt") {
        #It is preemptif
        if(!is.na(running)) {
          #if a process is running, we stack him because we are in preemption mode, and then stack also the next arrival. 
          waiting <<- c(waiting,running) #it stacks the current process, if t==t1[next_arrival]
          #interrupted = rbind(interrupted, data.frame(id=running, when=t, remaining=remaining[running]))
        }
        running <<- NA #We set it to NA as if no process is running
      }
      #preemptif or not we stack the next arrival
      waiting <<- c(waiting,next_arrival)
      next_arrival <<- next_arrival+1 
      if(is.na(running)) { run_task() } #if it was preemtpif let run the next arrival, by unstack it
    }

    #### Main simulation loop
    while(TRUE) { 
      #dt is the time we will minus the remaning running process time
      # Look for next event
      dt = NA
      #have we reached the number max of process arrival ?
      if(next_arrival <=n) { dt = min(dt ,(t1[next_arrival]-t), na.rm=T ) } #dt=t1[..]-t it's a bit akward to take the min with dt because NA are deleted. Notice that t1[next_arrival]-t=dt is the next process arrival time - current time. So this is the elapsed time
      
      #is some process running ? if so, we finish executing it if its remaining time is lower than the delta time of the next arrival
      if(!is.na(running))  { dt = min(dt,remaining[running], na.rm=T) }
      
      #we've reached the max of process (no next arrival) and no process is running, we take off
      if(is.na(dt)) { break }
      
      # Update state
      t=t+dt
      if(!is.na(running)) { 
        # if a process is running, we subtract him dt time
        remaining[running] = remaining[running] - dt
        used[running] = used[running] + dt
        if(remaining[running]<=0) {
          #if the process is finished, we note the finish time
          t2[running] = t
          running = NA
          
          #the process is finished, it unstacks the last process and it launchs it depending on the policy chosen (resume, restart, restart with lower time), and affect remaining[running] to the corresponding time service
          run_task()
        }
      }
      
      if((next_arrival<=n) & (t==t1[next_arrival])) {
        #if this is time for the next arrival
        push_task() #insert the next_arrival task to the waiting list and run it if there is preemption
      }
      
    }
    
    #count the number of times the system is empty
    for(i in 2:n) {
      if ( t1[i]>t2[i-1]) {
        sys_vide = sys_vide + 1
      }
    }
    
    list (jobs = data.frame(arrival = t1, completion=t2, service=used, theoricService=S, response=(t2-t1)), 
          sys_vide = sys_vide)
}    

```


Fixons nous une valeur X = 1
```{r}

set.seed(10)
lambda_min  = 0.1
lambda_max  = 0.95
lambdas     = c(.2, .4, .6, .8) #seq(lambda_min, lambda_max, step)
step        = 0.05
n           = 10000
x           = 1
y           = 1
policies    = c("srpt_pmtn","spt_pmtn", "spt")

df = data.frame()
for(policy in policies){ 
  for(lambda in lambdas) {
      route=FileLIFO(n, lambda, typeservice="exp", x, y, policy)
      tmp=route$jobs
      tmp$mode = policy
      tmp$lambda = lambda
      tmp$id=1:length(tmp$arrival)
      tmp$n = n
      tmp$sys_vide = route$sys_vide
      tmp$sys_interrupted=(tmp$n-tmp$sys_vide)
      df = rbind(df, tmp)
  }
}


library(plyr)
res = ddply(df, c("mode", "lambda", "n", "sys_vide", "sys_interrupted"), summarize, serviceM= mean(service), sd_service=sd(service), responseM=mean(response), sd_response=sd(response))

```

```{r}

ggplot(data=res, aes(x = lambda, y = responseM, color = mode, shape = mode)) + 
  geom_line() +
  geom_point() + 
  geom_errorbar(width = 0.02, aes(x = lambda, y = responseM, ymin = responseM - 2 * sd_response/sqrt(n), ymax = responseM + 2 * sd_response/sqrt(n))) + 
  geom_vline(xintercept = 1) +
  geom_hline(yintercept = 1) +
  theme_bw() +
  xlab("lamba") +
  ylab("Temps de réponse moyen") +
  ggtitle("Influence du taux d'arrivé (lambda) sur le temps de réponse")
```
